### ISSUE TITLE
插件中的Activity使用singleInstance模式，启动崩溃

### ISSUE THREAD

**Issue by trisiffer** [wequick/Small#70]
插件中的Activity在使用singleInstance模式，放到后台，清空数据或者等待后台被系统杀死的时候，再从近期任务记录中进入该activity会出现
 Caused by: java.lang.ClassNotFoundException: Didn't find class "net.wequick.small.A.3$3" on path: DexPathList[[zip file "/data/app/net.wequick.example.small-2.apk"],nativeLibraryDirectories=[/data/app-lib/net.wequick.example.small-2, /vendor/lib, /system/lib, /data/datalib]]
的错误。

**Comment by galenlin** [comment]
解决方法：在宿主application.onCreate加入`Small.preSetUp'方法，用来处理非正常退出后的恢复工作。

see 5bb4e19

**Comment by androidzhangfm** [comment]
Caused by:
5 java.lang.ClassNotFoundException:Didn't find class "net.wequick.small.A20" on path: DexPathList[[zip file "/data/user/0/com.jingdong.pdj/files/hotfix/rocoo_0.dex", zip file "/data/app/com.jingdong.pdj-2/base.apk"],nativeLibraryDirectories=[/data/app/com.jingdong.pdj-2/lib/arm, /data/app/com.jingdong.pdj-2/base.apk!/lib/armeabi-v7a, /vendor/lib, /system/lib]]
6 dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
7 java.lang.ClassLoader.loadClass(ClassLoader.java:511)
8 java.lang.ClassLoader.loadClass(ClassLoader.java:469)
9 android.app.Instrumentation.newActivity(Instrumentation.java:1070)
10 android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2355)
11 android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2517)
12 android.app.ActivityThread.-wrap11(ActivityThread.java)
13 android.app.ActivityThread$H.handleMessage(ActivityThread.java:1378)
14 android.os.Handler.dispatchMessage(Handler.java:102)

**Comment by androidzhangfm** [comment]
bugly检测有占坑的activity没有找到，是什么原因呢
